name: Check

on:
  push:
    branches:
      - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v4
      - name: fetch GraphQL schema
        uses: actions/checkout@v4
        with:
          repository: PromptPal/PromptPal
          path: ./PromptPal
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Build
        run: |
          sed -i 's/\.\.\/PromptPal\/schema\/schema\.gql/.\/PromptPal\/schema\/schema\.gql/g' ./codegen.ts
          cat ./codegen.ts
          pnpm install
          pnpm run g
          pnpm run build
      - name: Test
        run: pnpm run test:cov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=promptpal-web
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}