name: Check

on:
  push:
    branches:
      - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
      - name: fetch GraphQL schema
        uses: actions/checkout@v4
        with:
          repository: PromptPal/PromptPal
          path: ./PromptPal
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Build
        run: |
          sed -i 's/\.\.\/PromptPal\/schema\/schema\.gql/.\/PromptPal\/schema\/schema\.gql/g' ./codegen.ts
          cat ./codegen.ts
          pnpm install
          pnpm run g
          pnpm run build
      - name: Test
        run: pnpm run test
