name: Build and Release

on:
  push:
    branches:
      - master

permissions:
  contents: write # to create release commit (google-github-actions/release-please-action)
  pull-requests: write # to create release PR (google-github-actions/release-please-action)

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
      - uses: actions/checkout@v4
      - name: fetch GraphQL schema
        uses: actions/checkout@v4
        with:
          repository: PromptPal/PromptPal
          path: ./PromptPal
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Prepare
        run: |
          sed -i 's/\.\.\/PromptPal\/schema\/schema\.gql/.\/PromptPal\/schema\/schema\.gql/g' ./codegen.ts
          pnpm install
          pnpm run g
      - name: Build
        env:
          NODE_ENV: production
          VITE_HTTP_ENDPOINT: ''
        run: |
          pnpm run build
      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./dist-zip/dist.zip